### ISSUE TITLE
Exception with IDEA 14.1

### ISSUE THREAD

**Issue by mattnathan** [ukcrpb6/guava-postfix-plugin#18]
```
com.intellij.codeInsight.template.postfix.templates.PostfixTemplateWithExpressionSelector.<init>(Ljava/lang/String;Ljava/lang/String;Lcom/intellij/codeInsight/template/postfix/templates/PostfixTemplatePsiInfo;Lcom/intellij/openapi/util/Condition;)V
java.lang.NoSuchMethodError: com.intellij.codeInsight.template.postfix.templates.PostfixTemplateWithExpressionSelector.<init>(Ljava/lang/String;Ljava/lang/String;Lcom/intellij/codeInsight/template/postfix/templates/PostfixTemplatePsiInfo;Lcom/intellij/openapi/util/Condition;)V
	at uk.co.drache.intellij.codeinsight.postfix.internal.RichTopmostStringBasedPostfixTemplate.<init>(RichTopmostStringBasedPostfixTemplate.java:46)
	at uk.co.drache.intellij.codeinsight.postfix.templates.CheckArgumentPostfixTemplate.<init>(CheckArgumentPostfixTemplate.java:37)
	at uk.co.drache.intellij.codeinsight.postfix.GuavaPostfixTemplateProvider.<init>(GuavaPostfixTemplateProvider.java:52)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:58)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:75)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:68)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:63)
	at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.instantiateExtension(CustomLoadingExtensionPointBean.java:47)
	at com.intellij.lang.LanguageExtensionPoint.access$000(LanguageExtensionPoint.java:28)
	at com.intellij.lang.LanguageExtensionPoint$1.compute(LanguageExtensionPoint.java:42)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:36)
	at com.intellij.lang.LanguageExtensionPoint.getInstance(LanguageExtensionPoint.java:53)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:154)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:127)
	at com.intellij.codeInsight.template.postfix.templates.LanguagePostfixTemplate.buildExtensions(LanguagePostfixTemplate.java:38)
	at com.intellij.codeInsight.template.postfix.templates.LanguagePostfixTemplate.buildExtensions(LanguagePostfixTemplate.java:26)
	at com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:115)
	at com.intellij.lang.LanguageExtension.allForLanguage(LanguageExtension.java:71)
	at com.intellij.codeInsight.template.postfix.templates.PostfixLiveTemplate.isApplicable(PostfixLiveTemplate.java:163)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl.isApplicable(TemplateManagerImpl.java:309)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl.listApplicableCustomTemplates(TemplateManagerImpl.java:578)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor.a(LiveTemplateCompletionContributor.java:152)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor.access$100(LiveTemplateCompletionContributor.java:50)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2$1.consume(LiveTemplateCompletionContributor.java:94)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2$1.consume(LiveTemplateCompletionContributor.java:90)
	at com.intellij.codeInsight.completion.CompletionResultSet.passResult(CompletionResultSet.java:69)
	at com.intellij.codeInsight.completion.CompletionResultSet$1.consume(CompletionResultSet.java:119)
	at com.intellij.codeInsight.completion.CompletionResultSet$1.consume(CompletionResultSet.java:115)
	at com.intellij.codeInsight.completion.CompletionResultSet.passResult(CompletionResultSet.java:69)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl$CompletionResultSetImpl.addElement(CompletionServiceImpl.java:134)
	at com.intellij.codeInsight.completion.JavaCompletionData.fillCompletions(JavaCompletionData.java:463)
	at com.intellij.codeInsight.completion.Java18CompletionData.fillCompletions(Java18CompletionData.java:54)
	at com.intellij.codeInsight.completion.JavaCompletionContributor.a(JavaCompletionContributor.java:388)
	at com.intellij.codeInsight.completion.JavaCompletionContributor.fillCompletionVariants(JavaCompletionContributor.java:238)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:84)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:135)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:128)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:115)
	at com.intellij.codeInsight.completion.JavaNoVariantsDelegator.fillCompletionVariants(JavaNoVariantsDelegator.java:46)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:84)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:135)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:128)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:90)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:154)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:84)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:115)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:787)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$1000(CompletionProgressIndicator.java:89)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:769)
	at com.intellij.codeInsight.completion.AsyncCompletion$1$1$1.run(CompletionThreading.java:93)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:881)
	at com.intellij.codeInsight.completion.AsyncCompletion$1$1.run(CompletionThreading.java:88)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$3.run(ProgressManagerImpl.java:193)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:282)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:232)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:180)
	at com.intellij.codeInsight.completion.AsyncCompletion$1.run(CompletionThreading.java:84)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:408)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)



java.lang.NoSuchMethodError: com.intellij.codeInsight.template.postfix.templates.PostfixTemplateWithExpressionSelector.<init>(Ljava/lang/String;Ljava/lang/String;Lcom/intellij/codeInsight/template/postfix/templates/PostfixTemplatePsiInfo;Lcom/intellij/openapi/util/Condition;)V
	at uk.co.drache.intellij.codeinsight.postfix.internal.RichTopmostStringBasedPostfixTemplate.<init>(RichTopmostStringBasedPostfixTemplate.java:46)
	at uk.co.drache.intellij.codeinsight.postfix.templates.CheckArgumentPostfixTemplate.<init>(CheckArgumentPostfixTemplate.java:37)
	at uk.co.drache.intellij.codeinsight.postfix.GuavaPostfixTemplateProvider.<init>(GuavaPostfixTemplateProvider.java:52)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:58)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:75)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:68)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:63)
	at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.instantiateExtension(CustomLoadingExtensionPointBean.java:47)
	at com.intellij.lang.LanguageExtensionPoint.access$000(LanguageExtensionPoint.java:28)
	at com.intellij.lang.LanguageExtensionPoint$1.compute(LanguageExtensionPoint.java:42)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:36)
	at com.intellij.lang.LanguageExtensionPoint.getInstance(LanguageExtensionPoint.java:53)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:154)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:127)
	at com.intellij.codeInsight.template.postfix.templates.LanguagePostfixTemplate.buildExtensions(LanguagePostfixTemplate.java:38)
	at com.intellij.codeInsight.template.postfix.templates.LanguagePostfixTemplate.buildExtensions(LanguagePostfixTemplate.java:26)
	at com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:115)
	at com.intellij.lang.LanguageExtension.allForLanguage(LanguageExtension.java:71)
	at com.intellij.codeInsight.template.postfix.templates.PostfixLiveTemplate.isApplicable(PostfixLiveTemplate.java:163)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl.isApplicable(TemplateManagerImpl.java:309)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl.listApplicableCustomTemplates(TemplateManagerImpl.java:578)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor.a(LiveTemplateCompletionContributor.java:152)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor.access$100(LiveTemplateCompletionContributor.java:50)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2$1.consume(LiveTemplateCompletionContributor.java:94)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2$1.consume(LiveTemplateCompletionContributor.java:90)
	at com.intellij.codeInsight.completion.CompletionResultSet.passResult(CompletionResultSet.java:69)
	at com.intellij.codeInsight.completion.CompletionResultSet$1.consume(CompletionResultSet.java:119)
	at com.intellij.codeInsight.completion.CompletionResultSet$1.consume(CompletionResultSet.java:115)
	at com.intellij.codeInsight.completion.CompletionResultSet.passResult(CompletionResultSet.java:69)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl$CompletionResultSetImpl.addElement(CompletionServiceImpl.java:134)
	at com.intellij.codeInsight.completion.JavaCompletionData.b(JavaCompletionData.java:680)
	at com.intellij.codeInsight.completion.JavaCompletionData.fillCompletions(JavaCompletionData.java:529)
	at com.intellij.codeInsight.completion.Java18CompletionData.fillCompletions(Java18CompletionData.java:54)
	at com.intellij.codeInsight.completion.JavaCompletionContributor.a(JavaCompletionContributor.java:388)
	at com.intellij.codeInsight.completion.JavaCompletionContributor.fillCompletionVariants(JavaCompletionContributor.java:238)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:84)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:135)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:128)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:115)
	at com.intellij.codeInsight.completion.JavaNoVariantsDelegator.fillCompletionVariants(JavaNoVariantsDelegator.java:46)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:84)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:135)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:128)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:90)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:154)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:84)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:115)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:787)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$1000(CompletionProgressIndicator.java:89)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:769)
	at com.intellij.codeInsight.completion.AsyncCompletion$1$1$1.run(CompletionThreading.java:93)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:881)
	at com.intellij.codeInsight.completion.AsyncCompletion$1$1.run(CompletionThreading.java:88)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$3.run(ProgressManagerImpl.java:193)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:282)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:232)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:180)
	at com.intellij.codeInsight.completion.AsyncCompletion$1.run(CompletionThreading.java:84)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:408)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

**Comment by ukcrpb6** [comment]
More changes to the postfix api, have updated to support the most recent changes

https://github.com/ukcrpb6/guava-postfix-plugin/releases/tag/v1.1.1alpha
